name: Node CI

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: npm install and build
      run: |
        npm ci
        npm run build --if-present
      env:
        CI: true
    - name: Theme data
      uses: actions/upload-artifact@v1
      with:
        name: themedata
        path: dist
